# Generated by Django 3.1.5 on 2021-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='multiple',
            field=models.ManyToManyField(blank=True, default=None, related_name='field', to='question.Multiple'),
        ),
    ]
