# Generated by Django 3.1.5 on 2021-01-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210124_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(blank=True, choices=[('Text Area', 'Text Area'), ('Text Input', 'Text Input'), ('Multiple Choices', 'Multiple Choices'), ('Drop Down', 'Drop Down'), ('Check Box', 'Check Box')], default=None, max_length=30),
        ),
    ]
