# Generated by Django 3.1.5 on 2021-01-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
        ('question', '0003_auto_20210124_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='answer',
        ),
        migrations.AddField(
            model_name='form',
            name='response',
            field=models.ManyToManyField(blank=True, default=None, related_name='form', to='response.Response'),
        ),
        migrations.AddField(
            model_name='form',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
