# Generated by Django 3.1.5 on 2021-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20210124_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='field',
            field=models.ManyToManyField(related_name='form', to='question.Field'),
        ),
    ]
