# Generated by Django 3.1.5 on 2021-01-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20210124_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='slug',
        ),
    ]
