# Generated by Django 3.1.5 on 2021-01-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_remove_form_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255, unique=True),
        ),
    ]
