# Generated by Django 3.1.5 on 2021-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_response_code'),
        ('question', '0007_form_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='document_title',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='form',
            name='file_name',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='form',
            name='text_completion',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='form',
            name='text_container1',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='form',
            name='text_container2',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='form',
            name='response',
            field=models.ManyToManyField(related_name='form', to='response.Response'),
        ),
    ]
