# Generated by Django 3.1.5 on 2021-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_response_code'),
        ('question', '0008_auto_20210124_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='response',
            field=models.ManyToManyField(blank=True, default=None, related_name='form', to='response.Response'),
        ),
    ]
