# Generated by Django 3.1.5 on 2021-01-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20210124_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='multiple',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='field', to='question.Multiple'),
        ),
        migrations.AlterField(
            model_name='field',
            name='variable',
            field=models.CharField(blank=True, choices=[('p', 'p'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('a', 'a')], default=None, max_length=10, null=True),
        ),
    ]
