# Generated by Django 3.1.5 on 2021-01-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_response', models.CharField(max_length=300)),
                ('answer', models.ManyToManyField(blank=True, default=None, related_name='form', to='response.Answer')),
            ],
        ),
    ]
