# Generated by Django 3.1.5 on 2021-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_response_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
    ]
