# Generated by Django 3.1.5 on 2021-01-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_response_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='code',
            new_name='slug',
        ),
    ]
