# Generated by Django 3.1.5 on 2021-01-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_auto_20210125_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='code',
            field=models.SlugField(blank=True, default=None, max_length=255, unique=True),
        ),
    ]
