# Generated by Django 3.1.5 on 2021-01-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_response_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='slug',
            field=models.CharField(max_length=300),
        ),
    ]
