# Generated by Django 3.1.5 on 2021-01-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0006_auto_20210125_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
