# Generated by Django 3.1.5 on 2021-01-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0007_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='field_type',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='answer',
            name='variable',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
